---

- name: Verify maven is installed
  yum: name={{ item }} state=installed
  with_items:
    - maven

- name: Checkout MPASSid
  git: repo=https://github.com/Digipalvelutehdas/MPASSid-proxy version={{ mpassid_co_version }} dest="{{ remote_user_home }}/MPASSid-proxy"
  become: yes
  become_user: "{{ build_user }}"

- name: MPASSid maven clean install
  command: mvn -f MPASSid-proxy/idp-mpass-parent/pom.xml clean install
  become: yes
  become_user: "{{ build_user }}"

- name: Copy shibsp flows in to place
  command: cp -r "{{ remote_user_home }}/MPASSid-proxy/idp-authn-impl-shibsp/target/idp-authn-impl-shibsp-{{ mpassid_version }}-bin/idp-authn-impl-shibsp-{{ mpassid_version }}/flows/" /opt/shibboleth-idp
  become_user: root

- name: Removing ShipSP flow it exists already
  file:
    state: absent
    path: /opt/shibboleth-idp/flows/authn/ShibSP

- name: Rename example flow path to ShipSP flow path
  command: mv /opt/shibboleth-idp/flows/authn/ShibExample /opt/shibboleth-idp/flows/authn/ShibSP
  become_user: root
  
- name: Rename example flow to ShipSP flow
  command: mv /opt/shibboleth-idp/flows/authn/ShibSP/shibexample-flow.xml /opt/shibboleth-idp/flows/authn/ShibSP/shibsp-flow.xml
  become_user: root

- name: Copy ShibSP configuration file, existing file is not replaced
  copy:  
    src: "{{ remote_user_home }}/MPASSid-proxy/idp-authn-impl-shibsp/target/idp-authn-impl-shibsp-{{ mpassid_version }}-bin/idp-authn-impl-shibsp-{{ mpassid_version }}/conf/shib-authn-config.xml"
    dest: /opt/shibboleth-idp/conf/authn/shib-authn-config.xml
    owner: root
    group: jetty
    mode: 0750
    remote_src: yes
    force: no

- name: Copy ShibSP idp-authn-api-shibsp.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/MPASSid-proxy/idp-authn-api-shibsp/target/idp-authn-api-shibsp-{{ mpassid_version }}.jar"
    dest: "/opt/shibboleth-idp/edit-webapp/WEB-INF/lib/idp-authn-api-shibsp.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy ShibSP idp-authn-impl-shibsp.jar for bulding new idp.war  
  copy:
    src: "{{ remote_user_home }}/MPASSid-proxy/idp-authn-impl-shibsp/target/idp-authn-impl-shibsp-{{ mpassid_version }}.jar"                                                                
    dest: "/opt/shibboleth-idp/edit-webapp/WEB-INF/lib/idp-authn-impl-shibsp.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Build new idp.war
  shell: source {{ environment_file }} && /opt/shibboleth-idp/bin/build.sh
  become_user: root

- name: Restart shibboleth idp 
  service:
    name: shibboleth-idp
    state: restarted

