language: java
jdk:
- oraclejdk8
before_script:
- git clone https://github.com/Digipalvelutehdas/MPASSid-proxy
- mvn install -f MPASSid-proxy/idp-mpass-parent
script: 
- mvn package -f idp-stepup-parent/pom.xml
after_success:
- mvn clean cobertura:cobertura coveralls:report -f idp-stepup-parent/pom.xml
