language: java
jdk:
- oraclejdk8
before_script:
- git clone https://github.com/Digipalvelutehdas/MPASSid-proxy
- mvn install -f MPASSid-proxy/pom.xml
script: 
- mvn package
after_success:
- mvn clean cobertura:cobertura coveralls:report
