language: java
jdk:
- oraclejdk8
before_script:
- git clone https://github.com/Digipalvelutehdas/MPASSid-proxy
- cd MPASSid-proxy
- git checkout tags/MPASSid-proxy-0.9.0
- mvn install
- cd ..
script: 
- mvn package pom.xml
after_success:
- mvn clean cobertura:cobertura coveralls:report -f pom.xml
