- hosts: app

  vars:
    build_user: "{{ ansible_user }}"
    remote_user_home: "/home/{{ ansible_user }}/"
    idp_home: /opt/shibboleth-idp
    environment_file: /etc/default/shibboleth-idp

  remote_user: vagrant
  become: yes
  vars:
    remote_user_home: /home/vagrant
  roles:
    - cmprescott.xml
    - { role: keystore }
    - { role: CSCfi.apache }
    - { role: CSCfi.shibboleth-sp, shibbolethsp_signing: false }
    - { role: CSCfi.389-ds, dirsrv_password: testpword, replpwd: testpword, administration_domain: csc.fi, root: "dc=csc,dc=fi", supplier: "{{ service_name }}", mode: single, service_name: "{{ service_name }}", aci: "teppo@{{ service_name }}"}
    - { role: CSCfi.mariadb, mariadb_root_password: testpass }
    - { role: CSCfi.jetty }
    - { role: CSCfi.shibboleth-idp, shibbolethidp_version: 3.4.0, shibbolethidp_jetty_secure_port: 8444, scope: csc.fi, keystore_password: testpword }
    - { role: keystore, idp: true, keystore_password: testpword }
    #- { role: shibsp }
    - { role: configure, irsrv_rootdn: "cn=Directory Manager", dirsrv_password: testpword, replpwd: testpword, administration_domain: csc.fi, root: "dc=csc,dc=fi", supplier: "{{ service_name }}", mode: single, service_name: "{{ service_name }}", aci: "teppo@{{ service_name }}"}
  
  tasks:
    - name: initial packages
      yum: name={{ item }} state=present
      with_items:
        - nano
        - unzip
