---

- name: Verify git and maven are installed
  yum: name={{ item }} state=installed
  with_items:
    - maven
    - git

- name: Checkout shibboleth-idp-authn-shibsp
  git: repo=https://github.com/mpassid/shibboleth-idp-authn-shibsp dest="{{ remote_user_home }}/shibboleth-idp-authn-shibsp"
  become: yes
  become_user: "{{ build_user }}"

- name: shibboleth-idp-authn-shibsp maven clean install
  command: mvn -f shibboleth-idp-authn-shibsp/pom.xml clean install -DskipTests=true
  become: yes
  become_user: "{{ build_user }}"

- name: Copy shibsp flows in to place
  command: cp -r "{{ remote_user_home }}/shibboleth-idp-authn-shibsp/idp-authn-impl-shibsp/src/main/resources/flows/" {{ idp_home }}
  become_user: root

- name: Copy ShibSP configuration file
  copy:  
    src: "{{ remote_user_home }}/shibboleth-idp-authn-shibsp/idp-authn-impl-shibsp/src/main/resources/conf/shib-authn-config.xml"
    dest: "{{ idp_home }}/conf/authn/shib-authn-config.xml"
    owner: root
    group: jetty
    remote_src: true

- name: Locate idp-authn-api-shibsp.jar for bulding new idp.war
  find:
    paths: "{{ remote_user_home }}/shibboleth-idp-authn-shibsp/idp-authn-api-shibsp/target"
    patterns: "idp-authn-api-shibsp-*.jar"
  register: shibapifile


- name: Copy ShibSP idp-authn-api-shibsp.jar for bulding new idp.war
  copy:
    src: "{{ shibapifile.files[0].path }}"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/idp-authn-api-shibsp.jar"
    owner: root
    group: jetty
    remote_src: true

- name: Locate idp-authn-impl-shibsp.jar for bulding new idp.war
  find:
    paths: "{{ remote_user_home }}/shibboleth-idp-authn-shibsp/idp-authn-impl-shibsp/target"
    patterns: "idp-authn-impl-shibsp-*.jar"
  register: shibimplfile
 
- name: Copy ShibSP idp-authn-impl-shibsp.jar for bulding new idp.war  
  copy:
    src: "{{ shibimplfile.files[0].path }}"                                                                
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/idp-authn-impl-shibsp.jar"
    owner: root
    group: jetty
    remote_src: true

- name: Build new idp.war
  shell: source {{ environment_file }} && "{{ idp_home }}/bin/build.sh"
  become_user: root

- name: Restart shibboleth idp 
  service:
    name: shibboleth-idp
    state: restarted

