---

- name: Verify necessary packages are installed
  yum: name={{ item }} state=installed
  with_items:
    - maven
    - unzip
    - java-1.8.0-openjdk-devel

- name: Checkout StepUp Proxy
  git: repo=https://github.com/CSCfi/stepup-proxy version={{ stepup_co_version }} dest="{{ remote_user_home }}/stepup-proxy"
  become: yes
  become_user: "{{ build_user }}"

- name: StepUp Proxy maven clean package
  command: mvn -f stepup-proxy/pom.xml clean package
  become: yes
  become_user: "{{ build_user }}"

- name: Ensure "{{ idp_home }}/flows/oidc/mfarequest/" dir exists
  file: path="{{ idp_home }}/flows/oidc/mfarequest/" state=directory

- name: Ensure "{{ idp_home }}/flows/authn/mfa/" dir exists
  file: path="{{ idp_home }}/flows/authn/mfa/" state=directory

- name: Ensure "{{ idp_home }}/flows/intercept/stepup/" dir exists
  file: path="{{ idp_home }}/flows/intercept/stepup/" state=directory

- name: Copy stepup flows, overwriting existing ones
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  with_items:
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/oidc/mfarequest/mfarequest-flow.xml", dest: "{{ idp_home }}/flows/oidc/mfarequest/mfarequest-flow.xml" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/authn/mfa/mfa-flow.xml", dest: "{{ idp_home }}/flows/authn/mfa/mfa-flow.xml" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/intercept/stepup/stepup-flow.xml", dest: "{{ idp_home }}/flows/intercept/stepup/stepup-flow.xml" }

- name: Copy stepup beans, preserving existing ones
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
    force: no
  with_items:
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/oidc/mfarequest/mfarequest-beans.xml", dest: "{{ idp_home }}/flows/oidc/mfarequest/mfarequest-beans.xml" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/authn/mfa/mfa-beans.xml", dest: "{{ idp_home }}/flows/authn/mfa/mfa-beans.xml" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/intercept/stepup/stepup-beans.xml", dest: "{{ idp_home }}/flows/intercept/stepup/stepup-beans.xml" }

- name: Copy stepup beans as exmple beans, overwriting existing ones
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  with_items:
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/oidc/mfarequest/mfarequest-beans.xml", dest: "{{ idp_home }}/flows/oidc/mfarequest/mfarequest-beans.xml.example" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/authn/mfa/mfa-beans.xml", dest: "{{ idp_home }}/flows/authn/mfa/mfa-beans.xml.example" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/flows/intercept/stepup/stepup-beans.xml", dest: "{{ idp_home }}/flows/intercept/stepup/stepup-beans.xml.example" }

- name: Ensure "{{ idp_home }}/views/authn/" dir exists
  file: path="{{ idp_home }}/views/authn/" state=directory

- name: Ensure "{{ idp_home }}/views/oidc/" dir exists
  file: path="{{ idp_home }}/views/oidc/" state=directory

- name: Copy stepup views, overwriting existing ones
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  with_items:
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/oidc/mfarequest-error.vm", dest: "{{ idp_home }}/views/oidc/mfarequest-error.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-backend-progress.vm", dest: "{{ idp_home }}/views/authn/mfa-backend-progress.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-backend.vm", dest: "{{ idp_home }}/views/authn/mfa-backend.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-condolences.vm", dest: "{{ idp_home }}/views/authn/mfa-condolences.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-managesimple.vm", dest: "{{ idp_home }}/views/authn/mfa-managesimple.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-manage.vm", dest: "{{ idp_home }}/views/authn/mfa-manage.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-performed.vm", dest: "{{ idp_home }}/views/authn/mfa-performed.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-register.vm", dest: "{{ idp_home }}/views/authn/mfa-register.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-startregister.vm", dest: "{{ idp_home }}/views/authn/mfa-startregister.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa.vm", dest: "{{ idp_home }}/views/authn/mfa.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/authn/mfa-wrongresponse.vm", dest: "{{ idp_home }}/views/authn/mfa-wrongresponse.vm" }
    - { src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/src/main/resources/views/intercept/stepup-error.vm", dest: "{{ idp_home }}/views/intercept/stepup-error.vm" }

- name: Copy stepup dependency twilio-7.1.0.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/twilio-7.1.0.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/twilio-7.1.0.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  
- name: Copy stepup dependency spring-security-crypto-4.1.3.RELEASE.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/spring-security-crypto-4.1.3.RELEASE.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/spring-security-crypto-4.1.3.RELEASE.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy stepup dependency oauth2-oidc-sdk-5.26.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/oauth2-oidc-sdk-5.26.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/oauth2-oidc-sdk-5.26.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Find current nimbus library
  shell: "ls {{ remote_user_home }}stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/nimbus-jose-jwt-*"
  register: nimbus_file

- name: Copy stepup dependency nimbus-jose-jwt-* for bulding new idp.war
  copy:
    src: "{{ item }}"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  with_items: "{{ nimbus_file.stdout_lines }}"

- name: Copy stepup dependency lang-tag-1.4.3.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/lang-tag-1.4.3.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/lang-tag-1.4.3.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy stepup dependency json-smart-1.3.1.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/json-smart-1.3.1.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/json-smart-1.3.1.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

#- name: Copy stepup dependency jackson-databind-2.4.3.jar for bulding new idp.war
#  copy:
#    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/jackson-databind-2.4.3.jar"
#    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/jackson-databind-2.4.3.jar"
#    owner: root
#    group: root
#    mode: 0644
#    remote_src: yes

#- name: Copy stepup dependency jackson-core-2.4.3.jar for bulding new idp.war
#  copy:
#    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/jackson-core-2.4.3.jar"
#    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/jackson-core-2.4.3.jar"
#    owner: root
#    group: root
#    mode: 0644
#    remote_src: yes

#- name: Copy stepup dependency jackson-annotations-2.4.3.jar for bulding new idp.war
#  copy:
#    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/jackson-annotations-2.4.3.jar"
#    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/jackson-annotations-2.4.3.jar"
#    owner: root
#    group: root
#    mode: 0644
#    remote_src: yes

- name: Copy stepup dependency googleauth-1.1.1.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/googleauth-1.1.1.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/googleauth-1.1.1.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy stepup dependency commons-lang3-3.4.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/commons-lang3-3.4.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/commons-lang3-3.4.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy stepup dependency commons-collections4-4.1.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/commons-collections4-4.1.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/commons-collections4-4.1.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy stepup dependency HikariCP-2.4.7.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/dependency/HikariCP-2.4.7.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/HikariCP-2.4.7.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy stepup idp-ssointerceptor-api-stepup.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-api-stepup/target/idp-ssointerceptor-api-stepup-{{ stepup_version }}.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/idp-ssointerceptor-api-stepup.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Copy stepup idp-ssointerceptor-impl-stepup.jar for bulding new idp.war
  copy:
    src: "{{ remote_user_home }}/stepup-proxy/idp-ssointerceptor-impl-stepup/target/idp-ssointerceptor-impl-stepup-{{ stepup_version }}.jar"
    dest: "{{ idp_home }}/edit-webapp/WEB-INF/lib/idp-ssointerceptor-impl-stepup.jar"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
    
#- name: load current httpclient to support Twilio
#  get_url:
#    url: http://www-eu.apache.org/dist//httpcomponents/httpclient/binary/httpcomponents-client-4.5.3-bin.zip
#    dest: "{{ remote_user_home }}"

#- unarchive:
#    src: "{{ remote_user_home }}/httpcomponents-client-4.5.3-bin.zip"
#    dest: "{{ remote_user_home }}"
#    remote_src: True

# TODO: use wildcard
#- copy:
#    src: "{{ remote_user_home }}/httpcomponents-client-4.5.3/lib/{{ item }}"
#    dest: "{{ idp_home }}/webapp/WEB-INF/lib/"
#    remote_src: True
#  with_items:
#    - httpcore-4.4.6.jar
#    - httpclient-cache-4.5.3.jar
#    - httpclient-4.5.3.jar

#- shell: "ls /opt/shibboleth-idp/webapp/WEB-INF/lib/httpc*-4.3*"
#  register: old_httpclient
  
#- file:
#    path: "{{ item }}"
#    state: absent
#  with_items: "{{ old_httpclient.stdout_lines }}"
  
#add copy of basic set of dependencies

- name: Build new idp.war
  shell: source {{ environment_file }} && "{{ idp_home }}/bin/build.sh"
  become_user: root

- name: Restart shibboleth idp
  service:
    name: shibboleth-idp
    state: restarted

