---

- name: Verify maven and unzip are installed
  yum: name={{ item }} state=installed
  with_items:
    - maven
    - unzip

- name: Checkout StepUp Proxy
  git: repo=https://github.com/CSCfi/stepup-proxy version={{ stepup_co_version }} dest="{{ remote_user_home }}/stepup-proxy"
  become: yes
  become_user: "{{ build_user }}"

- name: StepUp Proxy maven clean package
  command: mvn -f stepup-proxy/pom.xml clean package
  become: yes
  become_user: "{{ build_user }}"


