---
# step-up-proxy-deployment.yml

- hosts: mfa-dev

  vars:
    build_user: vagrant
    remote_user_home: /home/vagrant/
    idp_home: /opt/shibboleth-idp
    environment_file: /etc/default/shibboleth-idp

  become: yes
  
  
  pre_tasks:
    - name: install git (required)
      become: yes
      yum: name=git state=present
  
  roles:
    - cmprescott.xml
    - CSCfi.apache
    - CSCfi.shibboleth-sp
    - CSCfi.jetty
    - 
      role: CSCfi.shibboleth-idp
      shibbolethidp_jetty_ssl_port: 8443
      shibbolethidp_jetty_secure_port: 8443
    - mpassid
    - stepup-proxy
    
  tasks:
    - name: install some packages
      become: yes
      yum: state=present name={{ item }}
      with_items:
        - emacs-nox
        - unzip
      
    - name: selinux permissive
      lineinfile:
        dest: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=permissive'
  
    - name: set timezone to Europe/Helsinki
      timezone: name=Europe/Helsinki


  handlers:
    - name: restart shibd
      service: state=restarted name=shibd